### ISSUE TITLE
VS 2019 support

### ISSUE THREAD

**Issue by Christoph-Wagner** [einaregilsson/StopOnFirstBuildError#12]
I forked and updated for VS 2019 Preview here: https://github.com/Christoph-Wagner/StopOnFirstBuildError

I'd be happy to submit a PR for 2017/2019 support, but I can't test with older versions as I don't have those. And 2010 support is AFAIK generally not possible with 2019 extensions. Let me know how you want me to handle this. I'd also be happy to wait until 2019 is RTM.

**Comment by einaregilsson** [comment]
Thanks! Would this change work for the RTM? Or would we need to change some version numbers again when that comes out?

**Comment by Christoph-Wagner** [comment]
It should work for RTM unless they have to make some drastic changes for some reason ;)

**Comment by einaregilsson** [comment]
Ok, great, make a PR and I'll try to merge and get it out sometime in the next few days.

**Comment by jedidja** [comment]
Just went looking for this and happy to see @Christoph-Wagner already has solution ready for next week (or sometime soon) :)
