### ISSUE TITLE
VS2019 - Deprecated APIs

### ISSUE THREAD

**Issue by TonyValenti** [einaregilsson/StopOnFirstBuildError#14]
When trying to use this extension, Visual Studio warns me that it is using deprecated APIs and it points to this URL for additional information:
https://docs.microsoft.com/en-us/visualstudio/extensibility/synchronously-autoloaded-extensions?view=vs-2019

**Comment by einaregilsson** [comment]
Yeah, I'll try to get that fixed sometime soon. I don't use VS anymore myself though, so it might be a while before I get to it.

**Comment by shuelsmeier** [comment]
Hi, I have created a pull request that fixes this issue #15.

**Comment by einaregilsson** [comment]
Thanks! However, does it change it to only support VS2019? I usually try to support the last 1 or 2 versions as well. Does AsyncPackage only work in VS2019?

**Comment by shuelsmeier** [comment]
Hi, my first pull request supported just VS2019. AsyncPackage however works in VS2017 as well. I changed the nuget package Microsoft.VisualStudio.Shell.15.0 to Microsoft.VisualStudio.Shell.14.0 and the extension works in VS2017 :-).

**Comment by einaregilsson** [comment]
Thanks! It did give me startup errors though in both VS2017 and VS2019, but I made some minor changes and it's now published as version 2.2.1
