### ISSUE TITLE
Version 1.6 broke Visual Studio 2010 support

### ISSUE THREAD

**Issue by cremor** [einaregilsson/StopOnFirstBuildError#7]
Since I updated to 1.6 the extension doesn't load in Visual Studio 2010 SP1 any more. ActivityLog.xml shows the following error:
Could not load file or assembly 'Microsoft.VisualStudio.Shell.10.0, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.

That assembly doesn't exist on my system. I only have 'Microsoft.VisualStudio.Shell, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

A few additional notes:
* Your assembly version is still 1.5
* Your assembly now targets .NET 4.5. This won't be installed on machines with Visual Studio 2010, unless someone installed it manually or with Windows Update.

**Comment by einaregilsson** [comment]
Sorry about that. I don't have access to VS2010 anymore, so I can't build a version for it anymore. Unless I would get the SDK assemblies somehow and build directly against them. When I opened the project in VS2013 it automatically updated it to the latest SDK.

**Comment by cremor** [comment]
Ok, no big deal since 1.6 doesn't contain anything new for me anyway. But sadly I don't have the 1.5 installer file anymore. Do you still have it? If yes, could you please make it available somewhere?

**Comment by einaregilsson** [comment]
Unfortunately I don't have it anymore, I just uploaded it to the VS gallery, and they don't keep track of old versions. But if you have VS2010 installed and the VS SDK you can easily pull the source from here and build it yourself. There aren't gonna be any changes to this, ever, so you're no losing out on anything by building yourself.

**Comment by cremor** [comment]
Ok, I've now managed to build it myself by using the old .csproj file from before it was upgraded for VS2012. If you want, I could upload that somewhere. But note that I had to create a new key file for the assembly signing.

**Comment by einaregilsson** [comment]
Thanks for the offer. But I think I'll just change the extension to explicitly say that VS2010 is no longer supported, I can't build for it anymore which means that anytime I wanted to update anything I would have to get someone else to do the release build. People still on VS2010 will just have to build manually. But again, thanks for the offer :)

**Comment by einaregilsson** [comment]
Well, thanks to some genius that published older VS interop assemblies on NuGet I have now published version 1.7, which should support VS2010 and VS2012 again. If you could try it for me that would be great, I still don't have VS2010 or 12 to test on.

**Comment by cremor** [comment]
Confirmed, works again on VS2010. Thanks!
