### ISSUE TITLE
VS2017 support

### ISSUE THREAD

**Issue by ljani** [einaregilsson/StopOnFirstBuildError#9]
Thanks for the wonderful extension! Any love for VS2017 on the market place?

**Comment by einaregilsson** [comment]
I don't have VS 2017, or even a Windows machine right now, so probably not unless someone sends in a pull request :) . But probably it's just a matter of adding a new version number, unless they've dramatically changed the VS APIs.

**Comment by jwldnr** [comment]
I have created a pull request that adds Visual Studio 2017 support: #10 

"To support the new light-weight install of Visual Studio 2017, the VSIX extension manifest format has been updated to version 3 (VSIX v3)."

**Comment by einaregilsson** [comment]
Thanks! Am merging it now, will try to publish sometime today!

**Comment by einaregilsson** [comment]
Published at https://marketplace.visualstudio.com/items?itemName=EinarEgilsson.StopOnFirstBuildError  , big thanks to @jwldnr ! 👍
